# Generated by Django 2.1.7 on 2019-04-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('star', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('url', models.CharField(max_length=1000)),
                ('x', models.CharField(max_length=1000)),
                ('y', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourismId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('url', models.CharField(max_length=1000)),
                ('x', models.CharField(max_length=1000)),
                ('y', models.CharField(max_length=1000)),
            ],
        ),
    ]
